#!/bin/tcsh

set nonomatch

if (! -e ./FiberAxis) mkdir ./FiberAxis
if (! -e ./FiberAxisProfiles) mkdir ./FiberAxisProfiles

foreach i (./Fibers/*parametrized.vtk)
	if (! -e ./FiberAxis/$i:t:r_axis.vtk) then
		echo computing axis for fiber $i
		python ./compute_fiber_axis.py $i --legacy --outlier-sigma 4.0 --clip-factor 3.0 -o ./FiberAxis/$i:t:r_axis.vtk --profiles-dir ./Profiles/  --profiles-output-dir ./FiberAxisProfiles/
	endif
end

echo merging fiber axes
if (! -e ./FiberAxis_merged.vtk) then
	python ./merge_fibers.py ./FiberAxis
endif

if (! -e ./FiberAxisProfiles_merged.vtk) then
	python ./merge_fibers.py ./FiberAxisProfiles
endif

